# Generated by Django 4.2.2 on 2023-07-11 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_name', to='reactivos.laboratorios', verbose_name='laboratory'),
        ),
    ]
