# Generated by Django 4.2 on 2023-04-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reactivo',
            new_name='Reactive',
        ),
    ]
