# Generated by Django 4.2.3 on 2023-08-22 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fecha_registro',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ultima_actualizacion',
            new_name='last_update',
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_User', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_User', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
