# Generated by Django 5.0.1 on 2024-01-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
    ]
