# Generated by Django 4.2.3 on 2023-09-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='date_order',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de orden'),
        ),
    ]
