# Generated by Django 4.2.2 on 2023-07-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_alter_user_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsables',
            name='cc',
            field=models.IntegerField(default=18517322, verbose_name='Cédula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_name', to='reactivos.laboratorios', verbose_name='laboratorio'),
        ),
    ]
