# Generated by Django 4.2.3 on 2023-08-05 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='date_register',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha registro'),
            preserve_default=False,
        ),
    ]
