# Generated by Django 4.2.2 on 2023-06-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_almacenamiento_destinos_entradas_estados_facultades_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respelc',
            options={'verbose_name': 'Clasificación Respel', 'verbose_name_plural': 'Clasificación Respel'},
        ),
        migrations.AlterModelOptions(
            name='sga',
            options={'verbose_name': 'Codificiación SGA', 'verbose_name_plural': 'Codificiación SGA'},
        ),
        migrations.RenameField(
            model_name='reactivos',
            old_name='SGA',
            new_name='sga',
        ),
        migrations.AlterField(
            model_name='sga',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Codificiación SGA'),
        ),
    ]
