# Generated by Django 4.2 on 2023-04-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_rename_reactivo_reactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactive',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactive', to='reactivos.unity'),
        ),
    ]
