# Generated by Django 4.2.2 on 2023-07-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_marcas_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcas',
            options={},
        ),
    ]
