# Generated by Django 4.2.3 on 2023-08-22 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_rename_fecha_registro_user_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número de identificación'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número Telefónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_User', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
