# Generated by Django 4.2.3 on 2023-09-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_alter_entradas_date_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsables',
            name='cc',
            field=models.BigIntegerField(verbose_name='Cédula'),
        ),
    ]
