# Generated by Django 5.0.1 on 2024-01-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_alter_marcas_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenamientointerno',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='almacenamientointerno',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='almacenamientointerno',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='clasealmacenamiento',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='clasealmacenamiento',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='clasealmacenamiento',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Actualización'),
        ),
    ]
