# Generated by Django 4.2.2 on 2023-07-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0003_alter_marcas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcas',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
