# Generated by Django 4.2.3 on 2023-09-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0003_alter_responsables_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsables',
            name='aceptDataProcessing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aceptDataProcessing',
            field=models.BooleanField(default=True),
        ),
    ]
