# Generated by Django 5.0.1 on 2024-01-31 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0003_alter_almacenamientointerno_date_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasealmacenamiento',
            options={'verbose_name': 'Almacenamiento Interno', 'verbose_name_plural': 'Almacenamiento Interno'},
        ),
        migrations.AlterField(
            model_name='clasealmacenamiento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='clasealmacenamiento',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_storage_class', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
