# Generated by Django 4.2.2 on 2023-06-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0003_alter_respelc_options_alter_sga_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacenamiento',
            options={'verbose_name': 'Ubicación en Almacén', 'verbose_name_plural': 'Ubicación en Almacén'},
        ),
        migrations.RemoveField(
            model_name='entradas',
            name='wlocation',
        ),
    ]
