# Generated by Django 4.2.3 on 2023-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0003_rol_date_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
