# Generated by Django 4.2 on 2023-04-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0003_alter_reactive_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactive',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reactive',
            name='color',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reactive',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='reactive',
            name='subnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reactive',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactivos.unity'),
        ),
    ]
