# Generated by Django 4.2.2 on 2023-06-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0004_alter_almacenamiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarios',
            name='minstock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Ingrese el stock mínimo (puede ser nulo).', max_digits=7, null=True),
        ),
    ]
