# Generated by Django 4.2.3 on 2023-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0004_alter_user_id_number_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarios',
            name='minStockControl',
            field=models.BooleanField(default=True, verbose_name='Control de Stock Mínimo'),
        ),
    ]
