# Generated by Django 4.2.2 on 2023-07-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0004_alter_entradas_location_alter_entradas_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarios',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Inventario Actual'),
        ),
    ]
