# Generated by Django 4.2.3 on 2023-08-05 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0004_rol_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='date_register',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='rol',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_Rol', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rol_user', to='reactivos.rol', verbose_name='Rol'),
        ),
    ]
