# Generated by Django 4.2.3 on 2023-09-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0004_responsables_aceptdataprocessing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsables',
            old_name='aceptDataProcessing',
            new_name='acceptDataProcessing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aceptDataProcessing',
        ),
        migrations.AddField(
            model_name='user',
            name='acceptDataProcessing',
            field=models.BooleanField(default=True),
        ),
    ]
