# Generated by Django 5.0.1 on 2024-01-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0004_alter_clasealmacenamiento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasealmacenamiento',
            options={'verbose_name': 'Clase de Almacenamiento', 'verbose_name_plural': 'Clases de almacenamiento'},
        ),
    ]
