# Generated by Django 4.2.3 on 2023-08-05 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0005_rename_date_register_rol_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_Rol', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
