# Generated by Django 4.2 on 2023-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0005_alter_reactive_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
