# Generated by Django 4.2.3 on 2023-09-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0005_rename_aceptdataprocessing_responsables_acceptdataprocessing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsables',
            name='acceptDataProcessing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='acceptDataProcessing',
            field=models.BooleanField(default=False),
        ),
    ]
