# Generated by Django 4.2.3 on 2023-09-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0005_inventarios_minstockcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='order',
            field=models.CharField(max_length=300, verbose_name='Orden No.'),
        ),
    ]
