# Generated by Django 4.2.2 on 2023-06-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0005_inventarios_minstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='edate',
        ),
        migrations.AddField(
            model_name='inventarios',
            name='edate',
            field=models.DateField(default='2033-06-25', verbose_name='Fecha de vencimiento'),
            preserve_default=False,
        ),
    ]
