# Generated by Django 5.0.1 on 2024-02-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0005_alter_clasealmacenamiento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ubicacion', to='reactivos.ubicaciones', verbose_name='Asignatura/Ubicación'),
        ),
    ]
