# Generated by Django 5.0.1 on 2024-02-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0006_alter_entradas_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor'),
        ),
    ]
