# Generated by Django 4.2.2 on 2023-07-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0006_alter_entradas_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarios',
            name='weight',
            field=models.BigIntegerField(verbose_name='Inventario Actual'),
        ),
    ]
