# Generated by Django 4.2.2 on 2023-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0006_remove_entradas_edate_inventarios_edate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
