# Generated by Django 4.2.3 on 2023-08-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0006_rol_last_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidades',
            old_name='fecha_registro',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='unidades',
            old_name='ultima_actualizacion',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='unidades',
            old_name='user',
            new_name='user_create',
        ),
    ]
