# Generated by Django 4.2.3 on 2023-09-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0006_alter_responsables_acceptdataprocessing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsables',
            name='acceptDataProcessing',
            field=models.BooleanField(default=False, verbose_name='Acepta tratamiento de datos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='acceptDataProcessing',
            field=models.BooleanField(default=False, verbose_name='Acepta tratamiento de datos'),
        ),
    ]
