# Generated by Django 4.2.2 on 2023-07-17 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0006_almacenamiento_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
