# Generated by Django 4.2.3 on 2023-09-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0006_alter_entradas_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='order',
            field=models.CharField(max_length=255, verbose_name='Orden No.'),
        ),
    ]
