# Generated by Django 5.0.1 on 2024-02-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0007_alter_entradas_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarios',
            name='visibilit',
            field=models.BooleanField(default=True, verbose_name='Visibilidad'),
        ),
    ]
