# Generated by Django 4.2.2 on 2023-07-17 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0007_user_fecha_registro_user_ultima_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_trademark', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
