# Generated by Django 4.2.3 on 2023-09-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0007_alter_entradas_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='date_order',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de orden'),
        ),
    ]
