# Generated by Django 4.2 on 2023-04-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0007_rename_reactive_reactivos_rename_unity_unidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivos',
            name='subnumber',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
