# Generated by Django 4.2.3 on 2023-08-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0007_rename_fecha_registro_unidades_date_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidades',
            old_name='user_create',
            new_name='created_by',
        ),
    ]
