# Generated by Django 4.2.2 on 2023-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0007_alter_inventarios_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='weight',
            field=models.FloatField(verbose_name='Peso Reactivo'),
        ),
        migrations.AlterField(
            model_name='inventarios',
            name='weight',
            field=models.FloatField(verbose_name='Inventario Actual'),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='weight',
            field=models.FloatField(verbose_name='Peso Reactivo'),
        ),
    ]
