# Generated by Django 5.0.1 on 2024-02-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0008_inventarios_visibilit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventarios',
            old_name='visibilit',
            new_name='visibility',
        ),
    ]
