# Generated by Django 4.2.3 on 2023-09-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0008_entradas_date_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
