# Generated by Django 4.2.3 on 2023-09-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0008_entradas_inventarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='inventarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv', to='reactivos.inventarios', verbose_name='Id_Inventario'),
        ),
    ]
