# Generated by Django 4.2.2 on 2023-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0008_alter_entradas_weight_alter_inventarios_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventarios',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
