# Generated by Django 4.2.3 on 2023-08-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0008_rename_user_create_unidades_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcas',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='marcas',
            old_name='fecha_registro',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='marcas',
            old_name='ultima_actualizacion',
            new_name='last_update',
        ),
    ]
