# Generated by Django 4.2.2 on 2023-07-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0009_almacenamiento_last_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarios',
            name='unit',
        ),
    ]
