# Generated by Django 5.0.1 on 2024-02-13 13:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0009_rename_visibilit_inventarios_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudesExternas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios en el nombre.', regex='^[A-Za-z\\s]+$')], verbose_name='Nombres y apellidos')),
                ('subject', models.CharField(max_length=100, verbose_name='Asunto')),
                ('message', models.TextField(max_length=1000, verbose_name='Mensaje')),
                ('attach', models.FileField(blank=True, null=True, upload_to='solicitud_attachments/', verbose_name='Archivos adjunto')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactivos.laboratorios', verbose_name='Fecha y hora de solicitud')),
            ],
        ),
    ]
