# Generated by Django 4.2.3 on 2023-09-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0009_alter_entradas_inventarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradas',
            old_name='inventarios',
            new_name='inventario',
        ),
    ]
