# Generated by Django 4.2.3 on 2023-08-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0010_rename_user_estados_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respelc',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='respelc',
            old_name='fecha_registro',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='respelc',
            old_name='ultima_actualizacion',
            new_name='last_update',
        ),
    ]
