# Generated by Django 5.0.1 on 2024-02-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0010_solicitudesexternas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudesexternas',
            options={'verbose_name_plural': 'Solicitudes Externas'},
        ),
    ]
