# Generated by Django 4.2.2 on 2023-07-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0010_alter_entradas_price_alter_entradas_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad de entrada'),
        ),
        migrations.AlterField(
            model_name='inventarios',
            name='minstock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Ingrese el stock mínimo (puede ser nulo).', max_digits=8, null=True, verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='inventarios',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad en inventario'),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad de salida'),
        ),
    ]
