# Generated by Django 5.0.1 on 2024-02-13 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0011_alter_solicitudesexternas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesexternas',
            name='department',
            field=models.CharField(default=1, max_length=100, verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudesexternas',
            name='email',
            field=models.EmailField(default=1, max_length=254, validators=[django.core.validators.EmailValidator(allowlist=['@unal.edu.co'], message='El correo electrónico debe pertenecer al dominio @unal.edu.co.')], verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudesexternas',
            name='mobile_number',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(message='El número de móvil debe estar en el rango de 3000000000 a 3999999999.', regex='^[3-9]\\d{9}$')], verbose_name='Teléfono Móvil'),
            preserve_default=False,
        ),
    ]
