# Generated by Django 4.2.3 on 2023-09-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0011_salidas_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivos',
            name='cas',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código CAS'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
    ]
