# Generated by Django 4.2.3 on 2023-08-06 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0011_rename_user_respelc_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sga',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='sga',
            old_name='fecha_registro',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='sga',
            old_name='ultima_actualizacion',
            new_name='last_update',
        ),
        migrations.AlterField(
            model_name='sga',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_SGA', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
