# Generated by Django 4.2.3 on 2023-10-09 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0012_alter_reactivos_cas_alter_reactivos_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SGA',
            new_name='ClaseAlmacenamiento',
        ),
        migrations.RemoveField(
            model_name='reactivos',
            name='sga',
        ),
        migrations.AddField(
            model_name='reactivos',
            name='clase_almacenamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='reactivos.clasealmacenamiento', verbose_name='Clase Almacenamiento'),
            preserve_default=False,
        ),
    ]
