# Generated by Django 5.0.1 on 2024-02-13 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0012_solicitudesexternas_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesexternas',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El nombre y apellido debe incluir únicamente letras, máximo 50 caracteres.', regex='^[A-Za-z\\s]+$')], verbose_name='Nombres y apellidos'),
        ),
    ]
