# Generated by Django 4.2 on 2023-04-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0012_alter_reactivos_subnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.AlterModelOptions(
            name='reactivos',
            options={'verbose_name': 'Reactivo', 'verbose_name_plural': 'Reactivos'},
        ),
        migrations.AlterModelOptions(
            name='unidades',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
    ]
