# Generated by Django 4.2.3 on 2023-10-10 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0013_rename_sga_clasealmacenamiento_remove_reactivos_sga_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasealmacenamiento',
            options={'verbose_name': 'Clase de almacenamiento', 'verbose_name_plural': 'Clase de almacenamiento'},
        ),
        migrations.AlterModelOptions(
            name='respelc',
            options={'verbose_name': 'Almacenamiento Interno', 'verbose_name_plural': 'Almacenamiento Interno'},
        ),
        migrations.RenameField(
            model_name='reactivos',
            old_name='respel',
            new_name='almacenamiento_interno',
        ),
        migrations.AlterField(
            model_name='clasealmacenamiento',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_Clase_Alamcenamiento', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='clasealmacenamiento',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='respelc',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
