# Generated by Django 4.2 on 2023-04-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0013_marcas_alter_reactivos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
            },
        ),
    ]
