# Generated by Django 5.0.1 on 2024-02-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0014_configuracionsistema_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesexternas',
            name='accept_politics',
            field=models.BooleanField(default=False, verbose_name='PTDP'),
        ),
    ]
