# Generated by Django 5.0.1 on 2024-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0015_solicitudesexternas_accept_politics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesexternas',
            name='accept_politics',
            field=models.BooleanField(verbose_name='PTDP'),
        ),
    ]
