# Generated by Django 4.2.3 on 2023-10-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0015_rename_respelc_almacenamientointerno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivos',
            name='almacenamiento_interno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlmacenamientoInterno', to='reactivos.almacenamientointerno', verbose_name='Almacenamiento Interno'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='clase_almacenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClaseAlmacenamiento', to='reactivos.clasealmacenamiento', verbose_name='Clase Almacenamiento'),
        ),
    ]
