# Generated by Django 4.2.3 on 2023-10-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0016_alter_reactivos_almacenamiento_interno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactivos',
            name='color',
        ),
        migrations.RemoveField(
            model_name='reactivos',
            name='number',
        ),
        migrations.RemoveField(
            model_name='reactivos',
            name='subnumber',
        ),
    ]
