# Generated by Django 4.2 on 2023-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0016_responsables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsables',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
