# Generated by Django 5.0.1 on 2024-02-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0016_alter_solicitudesexternas_accept_politics'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesexternas',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
