# Generated by Django 4.2.3 on 2023-08-06 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0016_rename_user_destinos_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorios',
            old_name='fecha_registro',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='laboratorios',
            old_name='ultima_actualizacion',
            new_name='last_update',
        ),
        migrations.RemoveField(
            model_name='laboratorios',
            name='user',
        ),
        migrations.AddField(
            model_name='laboratorios',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='laboratorios',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_Lab', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
