# Generated by Django 4.2.3 on 2023-10-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0017_remove_reactivos_color_remove_reactivos_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivos',
            name='cas',
            field=models.CharField(max_length=20, verbose_name='Código CAS'),
        ),
    ]
