# Generated by Django 4.2 on 2023-04-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0017_alter_responsables_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('reference', models.CharField(max_length=255, verbose_name='Referencia')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Peso Reactivo')),
                ('containerweight', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Peso Recipiente')),
                ('containernumber', models.IntegerField(verbose_name='Numero Recipientes')),
                ('is_liquid', models.BooleanField(default=False, verbose_name='Es líquido')),
                ('observations', models.TextField(max_length=1000, verbose_name='Observaciones')),
                ('density', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='density_name', to='reactivos.reactivos', verbose_name='Densidad')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='reactivos.destinos', verbose_name='Destino')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='reactivos.responsables', verbose_name='Responsable')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_react', to='reactivos.reactivos', verbose_name='Nombre Reactivo')),
                ('schoolsubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssubject', to='reactivos.asignaturas', verbose_name='Asignatura')),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_trademark', to='reactivos.marcas', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
            },
        ),
    ]
