# Generated by Django 4.2 on 2023-04-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0018_salidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidas',
            name='out_reagent',
            field=models.DecimalField(decimal_places=4, default=12, max_digits=10, verbose_name='Total Salida'),
            preserve_default=False,
        ),
    ]
