# Generated by Django 4.2 on 2023-04-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0019_salidas_out_reagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidas',
            name='containernumber',
        ),
        migrations.RemoveField(
            model_name='salidas',
            name='containerweight',
        ),
    ]
