# Generated by Django 4.2.3 on 2023-08-06 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0019_rename_user_reactivos_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaginaInicio',
        ),
        migrations.RenameField(
            model_name='entradas',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='entradas',
            old_name='date',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='entradas',
            old_name='ultima_actualizacion',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='inventarios',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='inventarios',
            old_name='ultima_actualizacion',
            new_name='last_update',
        ),
        migrations.RemoveField(
            model_name='inventarios',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='inventarios',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradas',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_In', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='inventarios',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_Inventory', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
