# Generated by Django 4.2.3 on 2023-10-12 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0019_tiposolicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Asunto')),
                ('mensaje', models.TextField(max_length=1000)),
                ('tramitado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('tipo_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reactivos.tiposolicitud', verbose_name='Tipo de solicitud')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userSolicitud', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que envía')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
