# Generated by Django 4.2 on 2023-04-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0020_remove_salidas_containernumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidas',
            name='density',
        ),
    ]
