# Generated by Django 4.2.3 on 2023-08-06 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0020_delete_paginainicio_rename_user_entradas_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidas',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='salidas',
            old_name='date',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='salidas',
            old_name='ultima_actualizacion',
            new_name='last_update',
        ),
        migrations.AlterField(
            model_name='salidas',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateby_Out', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
