# Generated by Django 4.2 on 2023-04-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0021_remove_salidas_density'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactivos',
            name='density',
        ),
        migrations.AddField(
            model_name='reactivos',
            name='cas',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='subnumber',
            field=models.CharField(max_length=3),
        ),
    ]
