# Generated by Django 4.2.3 on 2023-10-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0022_solicitudes_fecha_tramite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='usuario',
        ),
    ]
