# Generated by Django 4.2 on 2023-04-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0023_reactivos_is_liquid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactivos',
            name='wlocation',
            field=models.CharField(default=2, max_length=255, verbose_name='Ubicación Almacén'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignaturas',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='cas',
            field=models.CharField(max_length=20, verbose_name='Código CAS'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='color',
            field=models.PositiveIntegerField(verbose_name='Color CGA'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='is_liquid',
            field=models.CharField(max_length=3, verbose_name='Es líquido'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='number',
            field=models.CharField(max_length=5, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='subnumber',
            field=models.CharField(max_length=3, verbose_name='Sub-número'),
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactive', to='reactivos.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='responsables',
            name='mail',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='responsables',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre Responsable'),
        ),
        migrations.AlterField(
            model_name='responsables',
            name='phone',
            field=models.BigIntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Unidad'),
        ),
    ]
