# Generated by Django 4.2.3 on 2023-10-17 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0023_remove_solicitudes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='usuario_tramita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserTramite', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Tramita'),
        ),
    ]
