# Generated by Django 4.2.3 on 2023-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0024_solicitudes_usuario_tramita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='archivos_adjuntos',
            field=models.ImageField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
