# Generated by Django 4.2 on 2023-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0024_reactivos_wlocation_alter_asignaturas_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidas',
            name='out_reagent',
        ),
        migrations.AddField(
            model_name='salidas',
            name='location',
            field=models.CharField(default=2, max_length=100, verbose_name='Ubicación Salida'),
            preserve_default=False,
        ),
    ]
