# Generated by Django 4.2.3 on 2023-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0025_alter_solicitudes_archivos_adjuntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='tramitado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
