# Generated by Django 4.2 on 2023-04-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0025_remove_salidas_out_reagent_salidas_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='is_liquid',
            field=models.CharField(max_length=3, verbose_name='Es líquido'),
        ),
    ]
