# Generated by Django 4.2.3 on 2023-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0026_alter_solicitudes_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Asunto'),
        ),
    ]
