# Generated by Django 4.2 on 2023-05-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0027_ubicaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='reactivos.ubicaciones', verbose_name='Ubicación'),
        ),
    ]
