# Generated by Django 4.2.3 on 2023-10-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0027_solicitudes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='asunto',
        ),
    ]
