# Generated by Django 4.2.3 on 2023-10-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0028_remove_solicitudes_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='archivos_adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
