# Generated by Django 4.2 on 2023-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0028_alter_salidas_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicaciones',
            options={'verbose_name': 'Ubicación/Asignaturas', 'verbose_name_plural': 'Ubicaciones/Asignaturas'},
        ),
        migrations.RemoveField(
            model_name='salidas',
            name='schoolsubject',
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Ubicación/Asignaturas'),
        ),
        migrations.DeleteModel(
            name='Asignaturas',
        ),
    ]
