# Generated by Django 4.2.3 on 2023-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0029_alter_solicitudes_archivos_adjuntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_solicitudes', models.PositiveIntegerField(default=2, verbose_name='Tiempo para depuración de solicitudes (días)')),
                ('tiempo_eventos', models.PositiveIntegerField(default=2, verbose_name='Tiempo para depuración de eventos (días)')),
                ('correo_administrador', models.EmailField(max_length=100, verbose_name='Correo del Administrador del Sistema')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
