# Generated by Django 4.2.3 on 2023-10-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0030_configuracionsistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'verbose_name': 'Configuración del aplicativo', 'verbose_name_plural': 'Configuraciones del aplicativo'},
        ),
    ]
