# Generated by Django 4.2 on 2023-05-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0030_alter_ubicaciones_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('reference', models.CharField(max_length=255, verbose_name='Referencia')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Peso Reactivo')),
                ('is_liquid', models.CharField(max_length=3, verbose_name='Es líquido')),
                ('observations', models.TextField(max_length=1000, verbose_name='Observaciones')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ubicacion', to='reactivos.ubicaciones', verbose_name='Ubicación')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='reactivos.responsables', verbose_name='Responsable')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_reactivo', to='reactivos.reactivos', verbose_name='Nombre Reactivo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orden', to='reactivos.destinos', verbose_name='Orden No.')),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_marca', to='reactivos.marcas', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
            },
        ),
    ]
