# Generated by Django 4.2.3 on 2023-10-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0031_alter_configuracionsistema_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarios',
            name='edate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
