# Generated by Django 4.2 on 2023-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0031_entradas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='order',
            field=models.CharField(max_length=255, verbose_name='Orden No.'),
        ),
    ]
