# Generated by Django 4.2 on 2023-05-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0032_alter_entradas_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactivos.marcas')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactivos.reactivos')),
            ],
            options={
                'verbose_name_plural': 'Inventarios',
            },
        ),
    ]
