# Generated by Django 4.2 on 2023-05-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0033_inventarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarios',
            name='fecha_registro',
        ),
    ]
