# Generated by Django 4.2 on 2023-05-12 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0034_remove_inventarios_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
