# Generated by Django 4.2.3 on 2023-10-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0035_eventos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='fecha_incio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de inicio'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='intervalo_tiempo',
            field=models.PositiveIntegerField(default=1, verbose_name='Tiempo de revisión de fechas de vencimiento'),
            preserve_default=False,
        ),
    ]
