# Generated by Django 4.2 on 2023-05-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0036_destinos_fecha_registro_marcas_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventarios',
            old_name='reactivo',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inventarios',
            old_name='marca',
            new_name='trademark',
        ),
        migrations.RenameField(
            model_name='inventarios',
            old_name='cantidad',
            new_name='weigth',
        ),
    ]
