# Generated by Django 4.2 on 2023-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0037_rename_reactivo_inventarios_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarios',
            name='weigth',
        ),
        migrations.AddField(
            model_name='inventarios',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Peso Reactivo'),
            preserve_default=False,
        ),
    ]
