# Generated by Django 4.2 on 2023-05-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0038_remove_inventarios_weigth_inventarios_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarios',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidad', to='reactivos.unidades', verbose_name='Unidades'),
            preserve_default=False,
        ),
    ]
