# Generated by Django 4.2.3 on 2023-11-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0038_configuracionsistema_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo_institucional',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
