# Generated by Django 4.2 on 2023-05-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0041_remove_entradas_is_liquid_remove_salidas_is_liquid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AlterField(
            model_name='reactivos',
            name='is_liquid',
            field=models.CharField(max_length=20, verbose_name='Presentación'),
        ),
    ]
