# Generated by Django 4.2.1 on 2023-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0043_remove_reactivos_is_liquid_reactivos_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Facultad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
    ]
