# Generated by Django 4.2.1 on 2023-05-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0044_facultades'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='facultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facultad', to='reactivos.facultades', verbose_name='Facultad'),
            preserve_default=False,
        ),
    ]
