# Generated by Django 4.2 on 2023-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0045_ubicaciones_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
