# Generated by Django 4.2 on 2023-06-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0046_alter_entradas_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
