# Generated by Django 4.2.2 on 2023-06-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0047_alter_salidas_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsables',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
