# Generated by Django 4.2.2 on 2023-06-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0049_entradas_price_alter_inventarios_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='edate',
            field=models.DateField(default='2023-05-23', verbose_name='Fecha de vencimiento'),
            preserve_default=False,
        ),
    ]
