# Generated by Django 4.2.2 on 2023-06-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0050_entradas_edate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='destination',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='reactivos.destinos', verbose_name='Destino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradas',
            name='nproject',
            field=models.CharField(default='1-001-B', max_length=15, verbose_name='Número de proyecto'),
            preserve_default=False,
        ),
    ]
