# Generated by Django 4.2.2 on 2023-06-08 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0051_entradas_destination_entradas_nproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarios',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
